### ISSUE TITLE
clang-tidy support

### ISSUE THREAD

**Issue by withzombies** [duckie/cpp_project_template#2]
clang-tidy has been adding a lot of checkers for the cpp core guidelines (as well as taking over all the clang-modernize checkers).

It'd be nice if this project template supported clang-tidy.

**Comment by duckie** [comment]
Hi

Yup, good idea, I think its pretty easy to add, I'll look into it very soon.

**Comment by duckie** [comment]
I pushed a first shot. Checkout the README about it. Tell me what you think :)

**Comment by withzombies** [comment]
Looks good.

You should enable some default checkers like `-checks=cppcore*`.

**Comment by duckie** [comment]
Just did with a configuration file to avoid forcing the user into it through the script.
